### ISSUE TITLE
foreman does not read yaml settings from /etc/foreman/plugin dir

### ISSUE THREAD

**Issue by nipendar** [MiamiOH/foreman_custom_tab#6]
foreman does not read yaml settings from /etc/foreman/plugin dir

tested in formean running in dev and prod i.e
- bundle exec foreman start
- RAILS_ENV=production foreman start

**Comment by edestecd** [comment]
We have tried this plugin in our prod environment, which is installed via rpm and the foreman installer and it does indeed read its config from there.

**Comment by edestecd** [comment]
Unless installed from rpm foreman does not use /etc, it reads everything locally.
So you can use the local paths to test, but the doc in README should remain unchanged, b/c most users of this plugin will be using it from the official rpm/deb etc packages.

**Comment by nipendar** [comment]
Ok, make sense. Readme still specifies to set it /etc/foreman/plugin. I
will remove the section where it talks about dev setup as a fallback.

Regards,
Nipendar
+1-513 885 4801

**Comment by nipendar** [comment]
No fix needed. Should work with foreman installed via rpm, debian package
